/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.petco.jkafka;

import java.util.Properties;
import java.util.concurrent.ExecutionException;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;

public class MessageProducer {

public static void main(String[] args) {
        // Configure Kafka producer properties
        Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:29092"); // Update with your Kafka broker address
        props.put("acks", "all");
        props.put("retries", 3);
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

        // Create Kafka producer
        Producer<String, String> producer = new KafkaProducer<>(props);

        // Produce some messages
        for (int i = 0; i < 10; i++) {
            String message = "Message " + i;
            ProducerRecord<String, String> record = new ProducerRecord<>("TEST_TOPIC", message); // Update with your Kafka topic
            try {
                RecordMetadata metadata = producer.send(record).get();
                System.out.println("Message sent to partition " + metadata.partition() + ", offset " + metadata.offset());
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }

        // Close the producer
        producer.close();
    }
}
